name: Daily Durations Calculations

on:
  schedule:
    - cron: "15 17 * * *"
  workflow_dispatch: {}

jobs:

  yield_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run durations script
        env:
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: python backend/duration_pipeline/duration_calculations.py
